/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedContactsIndexRouteImport } from './routes/_authenticated/contacts/index'
import { Route as AuthenticatedFeedbacksIndexRouteImport } from './routes/_authenticated/feedbacks/index'
import { Route as AuthenticatedGalleriesIndexRouteImport } from './routes/_authenticated/galleries/index'
import { Route as AuthenticatedGalleryCategoriesIndexRouteImport } from './routes/_authenticated/gallery-categories/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedInstructorsIndexRouteImport } from './routes/_authenticated/instructors/index'
import { Route as AuthenticatedLiveSessionsIndexRouteImport } from './routes/_authenticated/live-sessions/index'
import { Route as AuthenticatedLiveSessionsSessionIdRouteImport } from './routes/_authenticated/live-sessions/$sessionId'
import { Route as AuthenticatedLiveSessionsCreateRouteImport } from './routes/_authenticated/live-sessions/create'
import { Route as AuthenticatedRecordedOrdersIndexRouteImport } from './routes/_authenticated/recorded-orders/index'
import { Route as AuthenticatedRecordedOrdersOrderIdRouteImport } from './routes/_authenticated/recorded-orders/$orderId'
import { Route as AuthenticatedRecordedSessionsIndexRouteImport } from './routes/_authenticated/recorded-sessions/index'
import { Route as AuthenticatedRecordedSessionsRecordedSessionIdRouteImport } from './routes/_authenticated/recorded-sessions/$recordedSessionId'
import { Route as AuthenticatedRecordedSessionsCreateRouteImport } from './routes/_authenticated/recorded-sessions/create'
import { Route as AuthenticatedResourcesIndexRouteImport } from './routes/_authenticated/resources/index'
import { Route as AuthenticatedSessionBookingsIndexRouteImport } from './routes/_authenticated/session-bookings/index'
import { Route as AuthenticatedSessionCategoriesIndexRouteImport } from './routes/_authenticated/session-categories/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedTestimonialsIndexRouteImport } from './routes/_authenticated/testimonials/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContactsIndexRoute =
  AuthenticatedContactsIndexRouteImport.update({
    id: '/contacts/',
    path: '/contacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedbacksIndexRoute =
  AuthenticatedFeedbacksIndexRouteImport.update({
    id: '/feedbacks/',
    path: '/feedbacks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGalleriesIndexRoute =
  AuthenticatedGalleriesIndexRouteImport.update({
    id: '/galleries/',
    path: '/galleries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGalleryCategoriesIndexRoute =
  AuthenticatedGalleryCategoriesIndexRouteImport.update({
    id: '/gallery-categories/',
    path: '/gallery-categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstructorsIndexRoute =
  AuthenticatedInstructorsIndexRouteImport.update({
    id: '/instructors/',
    path: '/instructors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveSessionsIndexRoute =
  AuthenticatedLiveSessionsIndexRouteImport.update({
    id: '/live-sessions/',
    path: '/live-sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveSessionsSessionIdRoute =
  AuthenticatedLiveSessionsSessionIdRouteImport.update({
    id: '/live-sessions/$sessionId',
    path: '/live-sessions/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveSessionsCreateRoute =
  AuthenticatedLiveSessionsCreateRouteImport.update({
    id: '/live-sessions/create',
    path: '/live-sessions/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecordedOrdersIndexRoute =
  AuthenticatedRecordedOrdersIndexRouteImport.update({
    id: '/recorded-orders/',
    path: '/recorded-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecordedOrdersOrderIdRoute =
  AuthenticatedRecordedOrdersOrderIdRouteImport.update({
    id: '/recorded-orders/$orderId',
    path: '/recorded-orders/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecordedSessionsIndexRoute =
  AuthenticatedRecordedSessionsIndexRouteImport.update({
    id: '/recorded-sessions/',
    path: '/recorded-sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecordedSessionsRecordedSessionIdRoute =
  AuthenticatedRecordedSessionsRecordedSessionIdRouteImport.update({
    id: '/recorded-sessions/$recordedSessionId',
    path: '/recorded-sessions/$recordedSessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecordedSessionsCreateRoute =
  AuthenticatedRecordedSessionsCreateRouteImport.update({
    id: '/recorded-sessions/create',
    path: '/recorded-sessions/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourcesIndexRoute =
  AuthenticatedResourcesIndexRouteImport.update({
    id: '/resources/',
    path: '/resources/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionBookingsIndexRoute =
  AuthenticatedSessionBookingsIndexRouteImport.update({
    id: '/session-bookings/',
    path: '/session-bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionCategoriesIndexRoute =
  AuthenticatedSessionCategoriesIndexRouteImport.update({
    id: '/session-categories/',
    path: '/session-categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedTestimonialsIndexRoute =
  AuthenticatedTestimonialsIndexRouteImport.update({
    id: '/testimonials/',
    path: '/testimonials/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/live-sessions/$sessionId': typeof AuthenticatedLiveSessionsSessionIdRoute
  '/live-sessions/create': typeof AuthenticatedLiveSessionsCreateRoute
  '/recorded-orders/$orderId': typeof AuthenticatedRecordedOrdersOrderIdRoute
  '/recorded-sessions/$recordedSessionId': typeof AuthenticatedRecordedSessionsRecordedSessionIdRoute
  '/recorded-sessions/create': typeof AuthenticatedRecordedSessionsCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/contacts/': typeof AuthenticatedContactsIndexRoute
  '/feedbacks/': typeof AuthenticatedFeedbacksIndexRoute
  '/galleries/': typeof AuthenticatedGalleriesIndexRoute
  '/gallery-categories/': typeof AuthenticatedGalleryCategoriesIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/instructors/': typeof AuthenticatedInstructorsIndexRoute
  '/live-sessions/': typeof AuthenticatedLiveSessionsIndexRoute
  '/recorded-orders/': typeof AuthenticatedRecordedOrdersIndexRoute
  '/recorded-sessions/': typeof AuthenticatedRecordedSessionsIndexRoute
  '/resources/': typeof AuthenticatedResourcesIndexRoute
  '/session-bookings/': typeof AuthenticatedSessionBookingsIndexRoute
  '/session-categories/': typeof AuthenticatedSessionCategoriesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/testimonials/': typeof AuthenticatedTestimonialsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/live-sessions/$sessionId': typeof AuthenticatedLiveSessionsSessionIdRoute
  '/live-sessions/create': typeof AuthenticatedLiveSessionsCreateRoute
  '/recorded-orders/$orderId': typeof AuthenticatedRecordedOrdersOrderIdRoute
  '/recorded-sessions/$recordedSessionId': typeof AuthenticatedRecordedSessionsRecordedSessionIdRoute
  '/recorded-sessions/create': typeof AuthenticatedRecordedSessionsCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/contacts': typeof AuthenticatedContactsIndexRoute
  '/feedbacks': typeof AuthenticatedFeedbacksIndexRoute
  '/galleries': typeof AuthenticatedGalleriesIndexRoute
  '/gallery-categories': typeof AuthenticatedGalleryCategoriesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/instructors': typeof AuthenticatedInstructorsIndexRoute
  '/live-sessions': typeof AuthenticatedLiveSessionsIndexRoute
  '/recorded-orders': typeof AuthenticatedRecordedOrdersIndexRoute
  '/recorded-sessions': typeof AuthenticatedRecordedSessionsIndexRoute
  '/resources': typeof AuthenticatedResourcesIndexRoute
  '/session-bookings': typeof AuthenticatedSessionBookingsIndexRoute
  '/session-categories': typeof AuthenticatedSessionCategoriesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/testimonials': typeof AuthenticatedTestimonialsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/live-sessions/$sessionId': typeof AuthenticatedLiveSessionsSessionIdRoute
  '/_authenticated/live-sessions/create': typeof AuthenticatedLiveSessionsCreateRoute
  '/_authenticated/recorded-orders/$orderId': typeof AuthenticatedRecordedOrdersOrderIdRoute
  '/_authenticated/recorded-sessions/$recordedSessionId': typeof AuthenticatedRecordedSessionsRecordedSessionIdRoute
  '/_authenticated/recorded-sessions/create': typeof AuthenticatedRecordedSessionsCreateRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/contacts/': typeof AuthenticatedContactsIndexRoute
  '/_authenticated/feedbacks/': typeof AuthenticatedFeedbacksIndexRoute
  '/_authenticated/galleries/': typeof AuthenticatedGalleriesIndexRoute
  '/_authenticated/gallery-categories/': typeof AuthenticatedGalleryCategoriesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/instructors/': typeof AuthenticatedInstructorsIndexRoute
  '/_authenticated/live-sessions/': typeof AuthenticatedLiveSessionsIndexRoute
  '/_authenticated/recorded-orders/': typeof AuthenticatedRecordedOrdersIndexRoute
  '/_authenticated/recorded-sessions/': typeof AuthenticatedRecordedSessionsIndexRoute
  '/_authenticated/resources/': typeof AuthenticatedResourcesIndexRoute
  '/_authenticated/session-bookings/': typeof AuthenticatedSessionBookingsIndexRoute
  '/_authenticated/session-categories/': typeof AuthenticatedSessionCategoriesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/testimonials/': typeof AuthenticatedTestimonialsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/live-sessions/$sessionId'
    | '/live-sessions/create'
    | '/recorded-orders/$orderId'
    | '/recorded-sessions/$recordedSessionId'
    | '/recorded-sessions/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/contacts/'
    | '/feedbacks/'
    | '/galleries/'
    | '/gallery-categories/'
    | '/help-center/'
    | '/instructors/'
    | '/live-sessions/'
    | '/recorded-orders/'
    | '/recorded-sessions/'
    | '/resources/'
    | '/session-bookings/'
    | '/session-categories/'
    | '/settings/'
    | '/testimonials/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/live-sessions/$sessionId'
    | '/live-sessions/create'
    | '/recorded-orders/$orderId'
    | '/recorded-sessions/$recordedSessionId'
    | '/recorded-sessions/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/contacts'
    | '/feedbacks'
    | '/galleries'
    | '/gallery-categories'
    | '/help-center'
    | '/instructors'
    | '/live-sessions'
    | '/recorded-orders'
    | '/recorded-sessions'
    | '/resources'
    | '/session-bookings'
    | '/session-categories'
    | '/settings'
    | '/testimonials'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/live-sessions/$sessionId'
    | '/_authenticated/live-sessions/create'
    | '/_authenticated/recorded-orders/$orderId'
    | '/_authenticated/recorded-sessions/$recordedSessionId'
    | '/_authenticated/recorded-sessions/create'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/contacts/'
    | '/_authenticated/feedbacks/'
    | '/_authenticated/galleries/'
    | '/_authenticated/gallery-categories/'
    | '/_authenticated/help-center/'
    | '/_authenticated/instructors/'
    | '/_authenticated/live-sessions/'
    | '/_authenticated/recorded-orders/'
    | '/_authenticated/recorded-sessions/'
    | '/_authenticated/resources/'
    | '/_authenticated/session-bookings/'
    | '/_authenticated/session-categories/'
    | '/_authenticated/settings/'
    | '/_authenticated/testimonials/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts/': {
      id: '/_authenticated/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AuthenticatedContactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedbacks/': {
      id: '/_authenticated/feedbacks/'
      path: '/feedbacks'
      fullPath: '/feedbacks/'
      preLoaderRoute: typeof AuthenticatedFeedbacksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/galleries/': {
      id: '/_authenticated/galleries/'
      path: '/galleries'
      fullPath: '/galleries/'
      preLoaderRoute: typeof AuthenticatedGalleriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery-categories/': {
      id: '/_authenticated/gallery-categories/'
      path: '/gallery-categories'
      fullPath: '/gallery-categories/'
      preLoaderRoute: typeof AuthenticatedGalleryCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instructors/': {
      id: '/_authenticated/instructors/'
      path: '/instructors'
      fullPath: '/instructors/'
      preLoaderRoute: typeof AuthenticatedInstructorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-sessions/': {
      id: '/_authenticated/live-sessions/'
      path: '/live-sessions'
      fullPath: '/live-sessions/'
      preLoaderRoute: typeof AuthenticatedLiveSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-sessions/$sessionId': {
      id: '/_authenticated/live-sessions/$sessionId'
      path: '/live-sessions/$sessionId'
      fullPath: '/live-sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedLiveSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-sessions/create': {
      id: '/_authenticated/live-sessions/create'
      path: '/live-sessions/create'
      fullPath: '/live-sessions/create'
      preLoaderRoute: typeof AuthenticatedLiveSessionsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recorded-orders/': {
      id: '/_authenticated/recorded-orders/'
      path: '/recorded-orders'
      fullPath: '/recorded-orders/'
      preLoaderRoute: typeof AuthenticatedRecordedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recorded-orders/$orderId': {
      id: '/_authenticated/recorded-orders/$orderId'
      path: '/recorded-orders/$orderId'
      fullPath: '/recorded-orders/$orderId'
      preLoaderRoute: typeof AuthenticatedRecordedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recorded-sessions/': {
      id: '/_authenticated/recorded-sessions/'
      path: '/recorded-sessions'
      fullPath: '/recorded-sessions/'
      preLoaderRoute: typeof AuthenticatedRecordedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recorded-sessions/$recordedSessionId': {
      id: '/_authenticated/recorded-sessions/$recordedSessionId'
      path: '/recorded-sessions/$recordedSessionId'
      fullPath: '/recorded-sessions/$recordedSessionId'
      preLoaderRoute: typeof AuthenticatedRecordedSessionsRecordedSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recorded-sessions/create': {
      id: '/_authenticated/recorded-sessions/create'
      path: '/recorded-sessions/create'
      fullPath: '/recorded-sessions/create'
      preLoaderRoute: typeof AuthenticatedRecordedSessionsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources/': {
      id: '/_authenticated/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof AuthenticatedResourcesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session-bookings/': {
      id: '/_authenticated/session-bookings/'
      path: '/session-bookings'
      fullPath: '/session-bookings/'
      preLoaderRoute: typeof AuthenticatedSessionBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/session-categories/': {
      id: '/_authenticated/session-categories/'
      path: '/session-categories'
      fullPath: '/session-categories/'
      preLoaderRoute: typeof AuthenticatedSessionCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/testimonials/': {
      id: '/_authenticated/testimonials/'
      path: '/testimonials'
      fullPath: '/testimonials/'
      preLoaderRoute: typeof AuthenticatedTestimonialsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLiveSessionsSessionIdRoute: typeof AuthenticatedLiveSessionsSessionIdRoute
  AuthenticatedLiveSessionsCreateRoute: typeof AuthenticatedLiveSessionsCreateRoute
  AuthenticatedRecordedOrdersOrderIdRoute: typeof AuthenticatedRecordedOrdersOrderIdRoute
  AuthenticatedRecordedSessionsRecordedSessionIdRoute: typeof AuthenticatedRecordedSessionsRecordedSessionIdRoute
  AuthenticatedRecordedSessionsCreateRoute: typeof AuthenticatedRecordedSessionsCreateRoute
  AuthenticatedContactsIndexRoute: typeof AuthenticatedContactsIndexRoute
  AuthenticatedFeedbacksIndexRoute: typeof AuthenticatedFeedbacksIndexRoute
  AuthenticatedGalleriesIndexRoute: typeof AuthenticatedGalleriesIndexRoute
  AuthenticatedGalleryCategoriesIndexRoute: typeof AuthenticatedGalleryCategoriesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedInstructorsIndexRoute: typeof AuthenticatedInstructorsIndexRoute
  AuthenticatedLiveSessionsIndexRoute: typeof AuthenticatedLiveSessionsIndexRoute
  AuthenticatedRecordedOrdersIndexRoute: typeof AuthenticatedRecordedOrdersIndexRoute
  AuthenticatedRecordedSessionsIndexRoute: typeof AuthenticatedRecordedSessionsIndexRoute
  AuthenticatedResourcesIndexRoute: typeof AuthenticatedResourcesIndexRoute
  AuthenticatedSessionBookingsIndexRoute: typeof AuthenticatedSessionBookingsIndexRoute
  AuthenticatedSessionCategoriesIndexRoute: typeof AuthenticatedSessionCategoriesIndexRoute
  AuthenticatedTestimonialsIndexRoute: typeof AuthenticatedTestimonialsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLiveSessionsSessionIdRoute:
    AuthenticatedLiveSessionsSessionIdRoute,
  AuthenticatedLiveSessionsCreateRoute: AuthenticatedLiveSessionsCreateRoute,
  AuthenticatedRecordedOrdersOrderIdRoute:
    AuthenticatedRecordedOrdersOrderIdRoute,
  AuthenticatedRecordedSessionsRecordedSessionIdRoute:
    AuthenticatedRecordedSessionsRecordedSessionIdRoute,
  AuthenticatedRecordedSessionsCreateRoute:
    AuthenticatedRecordedSessionsCreateRoute,
  AuthenticatedContactsIndexRoute: AuthenticatedContactsIndexRoute,
  AuthenticatedFeedbacksIndexRoute: AuthenticatedFeedbacksIndexRoute,
  AuthenticatedGalleriesIndexRoute: AuthenticatedGalleriesIndexRoute,
  AuthenticatedGalleryCategoriesIndexRoute:
    AuthenticatedGalleryCategoriesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedInstructorsIndexRoute: AuthenticatedInstructorsIndexRoute,
  AuthenticatedLiveSessionsIndexRoute: AuthenticatedLiveSessionsIndexRoute,
  AuthenticatedRecordedOrdersIndexRoute: AuthenticatedRecordedOrdersIndexRoute,
  AuthenticatedRecordedSessionsIndexRoute:
    AuthenticatedRecordedSessionsIndexRoute,
  AuthenticatedResourcesIndexRoute: AuthenticatedResourcesIndexRoute,
  AuthenticatedSessionBookingsIndexRoute:
    AuthenticatedSessionBookingsIndexRoute,
  AuthenticatedSessionCategoriesIndexRoute:
    AuthenticatedSessionCategoriesIndexRoute,
  AuthenticatedTestimonialsIndexRoute: AuthenticatedTestimonialsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
